#cloud-config
hostname: ${hostname}
bootcmd:
  - echo "127.0.0.1 localhost" > /etc/hosts
apt_sources:
  - source: deb http://apt.puppetlabs.com $RELEASE PC1
    keyid: EF8D349F
    filename: puppetlabs.list
apt_update: true
apt_upgrade: true
packages:
  - puppet-agent=${puppet_agent_version}
  - git
locale: en_US.UTF-8
timezone: UTC
runcmd:
  - /opt/puppetlabs/puppet/bin/gem install r10k
  - git clone https://github.com/renaudhager/puppet-bootstrap.git /tmp/puppet-bootstrap
  - /opt/puppetlabs/bin/puppet apply /tmp/puppet-bootstrap/node.pp
  - /opt/puppetlabs/puppet/bin/r10k deploy environment --puppetfile -v
  - /opt/puppetlabs/bin/puppet apply /etc/puppetlabs/code/environments/production/site.pp --environment=${puppet_env}
  # Twice is better once
  - /opt/puppetlabs/bin/puppet apply /etc/puppetlabs/code/environments/production/site.pp --environment=${puppet_env}
final_message: "The system is up, after $UPTIME seconds"
